repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [ "--assume-in-merge" ]
      - id: no-commit-to-branch
        args: [ "--branch", "master", "--branch", "dev", "--pattern", "^(?!feat|fix|chore|ci|docs|style|refactor|perf|test).+" ]
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
        - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=120", "--ignore=E203", "--max-complexity=10" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
        - id: isort
          args: [ "--profile", "black" ]
          name: isort (python)
        - id: isort
          args: [ "--profile", "black" ]
          types: [ cython ]
          name: isort (cython)
        - id: isort
          args: [ "--profile", "black" ]
          types: [ pyi ]
          name: isort (pyi)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - "--strict"
          - "--namespace-packages"
          - "--explicit-package-bases"
          - "--install-types"
          - "--non-interactive"
          - "--pretty"
          - "--ignore-missing-imports"

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - "--convention"
          - "google"
          - "--add-select"
          - "D400,D401,D404"
          - "--explain"